language: ruby
rvm:
  - "2.3.0"
  - "2.5.1"
  - "jruby-1.7.23"
  - "jruby-9.1.17.0"
notifications:
  email:
    recipients:
      - D&ENewsFrameworksTeam@bbc.co.uk
    on_failure: change
    on_success: never
